DROP TABLE IF EXISTS booze;
DROP TABLE IF EXISTS boozeless;
DROP TABLE IF EXISTS ingredients;

CREATE TABLE booze (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE boozeless (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ingredients (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO booze (name) VALUES
  ('Absinthe'),
  ('Absolut Vodka'),
  ('Absolut citron'),
  ('Aftershock'),
  ('Amaretto'),
  ('Amaro Montenegro'),
  ('Apple Brandy'),
  ('Apple Schnapps'),
  ('Applejack'),
  ('Apricot Brandy'),
  ('Añejo Rum'),
  ('Bacardi'),
  ('Baileys Irish Cream'),
  ('Beer'),
  ('Black Rum'),
  ('Black Sambuca'),
  ('Blackberry Brandy'),
  ('Blackcurrant Schnapps'),
  ('Blackstrap rum'),
  ('Blended Scotch'),
  ('Blended Whiskey'),
  ('Blue Curacao'),
  ('Blueberry Schnapps'),
  ('Bourbon'),
  ('Brandy'),
  ('Campari'),
  ('Canadian Whisky'),
  ('Chambord Raspberry Liqueur'),
  ('Champagne'),
  ('Cherry Brandy'),
  ('Cherry Heering'),
  ('Cherry Liqueur'),
  ('Chocolate Liqueur'),
  ('Cider'),
  ('Cinnamon Schnapps'),
  ('Citrus Vodka'),
  ('Coconut Liqueur'),
  ('Coconut Rum'),
  ('Coffee Liqueur'),
  ('Cognac'),
  ('Cointreau'),
  ('Creme De Cassis'),
  ('Crown Royal'),
  ('Dark Rum'),
  ('Drambuie'),
  ('Dry Vermouth'),
  ('Everclear'),
  ('Firewater'),
  ('Frangelico'),
  ('Gin'),
  ('Gold Tequila'),
  ('Goldschlager'),
  ('Grand Marnier'),
  ('Grenadine'),
  ('Guinness'),
  ('Hazelnut liqueur'),
  ('Hot Damn'),
  ('Irish Whiskey'),
  ('Jack Daniels'),
  ('Jagermeister'),
  ('Jim Beam'),
  ('Johnnie Walker'),
  ('Kahlua'),
  ('Lager'),
  ('Light Rum'),
  ('Madeira'),
  ('Malibu Rum'),
  ('Martini Rosso'),
  ('Mezcal'),
  ('Midori'),
  ('Ouzo'),
  ('Peach Schnapps'),
  ('Peppermint Schnapps'),
  ('Pernod'),
  ('Port'),
  ('Prosecco'),
  ('Red Wine'),
  ('Ruby Port'),
  ('Rum'),
  ('Rye Whiskey'),
  ('Sambuca'),
  ('Sarsaparilla'),
  ('Schnapps'),
  ('Scotch'),
  ('Sherry'),
  ('Sloe Gin'),
  ('Southern Comfort'),
  ('Spiced Rum'),
  ('Sweet Vermouth'),
  ('Tequila'),
  ('Triple Sec'),
  ('Vermouth'),
  ('Vodka'),
  ('Whiskey'),
  ('Whisky'),
  ('Wine');

INSERT INTO boozeless (name) VALUES
  ('Vanilla Extract (Whiskey)'),
  ('Pineapple Juice (Rum)'),
  ('White Grape Juice (Vodka)'),
  ('Apricot Juice (Cognac)'),
  ('Apple Juice (Vermouth)'),
  ('Almond Extract (Amaretto)');

INSERT INTO ingredients (name) VALUES
  ('7-up'),
  ('Agave Syrup'),
  ('Apple Juice'),
  ('Apricot Nectar'),
  ('Beef Stock'),
  ('Blackberries'),
  ('Blood Orange'),
  ('Blueberries'),
  ('Brown Sugar'),
  ('Butter'),
  ('Caramel Sauce'),
  ('Carbonated Soft Drink'),
  ('Carbonated Water'),
  ('Cayenne Pepper'),
  ('Celery'),
  ('Cherry Juice'),
  ('Chocolate Ice-cream'),
  ('Chocolate Milk'),
  ('Chocolate Syrup'),
  ('Cinnamon'),
  ('Clamato Juice'),
  ('Cloves'),
  ('Club Soda'),
  ('Coca-Cola'),
  ('Coconut Milk'),
  ('Coffee'),
  ('Cola'),
  ('Corn Syrup'),
  ('Cranberry Juice'),
  ('Cream'),
  ('Crystal Light'),
  ('Dark Chocolate'),
  ('Diet Coke'),
  ('Dr. Pepper'),
  ('Egg'),
  ('Espresso'),
  ('Fruit Juice'),
  ('Gatorade'),
  ('Ginger Ale'),
  ('Grape juice'),
  ('Grapefruit Juice'),
  ('Half-and-half'),
  ('Heavy cream'),
  ('Honey'),
  ('Hot Chocolate'),
  ('Hot Sauce'),
  ('Jello'),
  ('Lemon Juice'),
  ('Lemonade'),
  ('Lime Juice'),
  ('Maple syrup'),
  ('Milk'),
  ('Olive Oil'),
  ('Orange Juice'),
  ('Papaya juice'),
  ('Peach juice'),
  ('Peppermint extract'),
  ('Pepsi Cola'),
  ('Pineapple Juice'),
  ('Pomegranate juice'),
  ('Powdered Sugar'),
  ('Red Bull'),
  ('Salt'),
  ('Soda Water'),
  ('Soy Milk'),
  ('Soy Sauce'),
  ('Sprite'),
  ('Sugar'),
  ('Sugar Syrup'),
  ('Sunny delight'),
  ('Sweet Cream'),
  ('Tabasco Sauce'),
  ('Tea'),
  ('Tomato Juice'),
  ('Vanilla Ice-Cream'),
  ('Vinegar'),
  ('lemon');
